import type { Difficulty } from "@prisma/client";
export type Q = { text: string; options: string[]; correctIndex: number;
  explanation: string; difficulty: Difficulty; category: string };

export const QUESTIONS: Q[] = [
  { text: "Which film marked SRK's Bollywood debut?",
    options: ["Deewana", "Raju Ban Gaya Gentleman", "Maya Memsaab", "Chamatkar"], correctIndex: 0,
    explanation: "'Deewana' (1992) was SRK's Bollywood debut.", difficulty: "EASY", category: "Career" },
  { text: "What is SRK's birth date?",
    options: ["2 November, 1964", "2 November, 1966", "2 November, 1965", "2 November, 1963"], correctIndex: 2,
    explanation: "Shah Rukh Khan was born on 2 November 1965.", difficulty: "MED", category: "Personal" },
  { text: "Which movie featured Raj & Simran?",
    options: ["Pardes", "KKHH", "DDLJ", "Dil Se"], correctIndex: 2,
    explanation: "Raj and Simran are the leads of 'Dilwale Dulhania Le Jayenge'.", difficulty: "EASY", category: "Movies" },
  { text: "Which SRK film won the National Award for Best Popular Film?",
    options: ["My Name Is Khan", "Chak De India", "Swades", "Main Hoon Na"], correctIndex: 1,
    explanation: "'Chak De! India' won the National Film Award for Best Popular Film Providing Wholesome Entertainment.", difficulty: "HARD", category: "Awards" },
  { text: "Which actress has appeared in the most films with SRK?",
    options: ["Kajol", "Juhi Chawla", "Rani Mukherji", "Deepika Padukone"], correctIndex: 1,
    explanation: "Juhi Chawla has shared the screen with SRK in the most films.", difficulty: "MED", category: "Movies" },
  { text: "Which was SRK's first film under the Red Chillies Entertainment banner?",
    options: ["Main Hoon Na", "Paheli", "Chalte Chalte", "Om Shanti Om"], correctIndex: 0,
    explanation: "'Main Hoon Na' (2004) was the first film produced under Red Chillies Entertainment.", difficulty: "MED", category: "Business" },
  { text: "Which university awarded Shah Rukh Khan his first honorary doctorate?",
    options: ["University of Edinburgh", "University of Bedfordshire", "University of Law", "La Trobe University"], correctIndex: 1,
    explanation: "The University of Bedfordshire awarded SRK his first honorary doctorate in 2009.", difficulty: "HARD", category: "Awards" },
  { text: "Which film revived SRK's box office dominance in 2023?",
    options: ["Jawan", "Pathaan", "Dunki", "Fan"], correctIndex: 1,
    explanation: "'Pathaan' (Jan 2023) marked his blockbuster box-office comeback.", difficulty: "EASY", category: "Movies" },
  { text: "Which SRK movie has the character Mohan Bhargava?",
    options: ["Raees", "Chak De", "Veer-Zaara", "Swades"], correctIndex: 3,
    explanation: "Mohan Bhargava is the NASA scientist lead in 'Swades'.", difficulty: "MED", category: "Movies" },
  { text: "What is the name of SRK's residence in Mumbai?",
    options: ["Jannat", "Mannat", "Khwaab", "Shanti"], correctIndex: 1,
    explanation: "His Mumbai bungalow is called 'Mannat'.", difficulty: "EASY", category: "Personal" },
  { text: "Identify the movie from: \"Beta ke haath lagane se pehle, baap se baat kar.\"",
    options: ["Kabhi Alvida Naa Kehna", "Ra One", "Jawan", "My Name Is Khan"], correctIndex: 2,
    explanation: "This dialogue is from 'Jawan' (2023).", difficulty: "MED", category: "Movies" },
  { text: "Which SRK movie features the song \"Mitwa\"?",
    options: ["DDLJ", "Dil To Pagal Hai", "Kabhi Alvida Naa Kehna", "Duplicate"], correctIndex: 2,
    explanation: "'Mitwa' is from 'Kabhi Alvida Naa Kehna' (2006).", difficulty: "MED", category: "Music" },
  { text: "Which SRK movie was released first in the list below?",
    options: ["Anjaam", "DDLJ", "Pardes", "Baazigar"], correctIndex: 3,
    explanation: "'Baazigar' (1993) came before Anjaam (1994), DDLJ (1995) and Pardes (1997).", difficulty: "MED", category: "Movies" },
  { text: "Which film featured SRK as both superstar and junior artist?",
    options: ["Duplicate", "Fan", "Zero", "Om Shanti Om"], correctIndex: 3,
    explanation: "In 'Om Shanti Om' he plays junior artist Om Prakash and superstar Om Kapoor.", difficulty: "MED", category: "Movies" },
  { text: "Which movie's climax happens in a hockey stadium?",
    options: ["Main Hoon Naa", "Happy New Year", "Chak De India", "Dil Se"], correctIndex: 2,
    explanation: "'Chak De! India' climaxes at the World Cup hockey final.", difficulty: "EASY", category: "Movies" },
  { text: "What was SRK's first television serial?",
    options: ["Circus", "Fauji", "Umeed", "Dil Dariya"], correctIndex: 1,
    explanation: "'Fauji' (1989) was the serial that first brought him fame.", difficulty: "MED", category: "Career" },
  { text: "In Swades, what is the name of the village?",
    options: ["Devpur", "Rampur", "Sonpur", "Charanpur"], correctIndex: 3,
    explanation: "The film is set in the village of Charanpur.", difficulty: "MED", category: "Movies" },
  { text: "Which SRK film had the tagline: \"A Story of a Lifetime... In a Heartbeat\"?",
    options: ["My Name Is Khan", "Veer-Zaara", "Kabhi Alvida Naa Kehna", "Kal Ho Naa Ho"], correctIndex: 3,
    explanation: "This is the tagline of 'Kal Ho Naa Ho'.", difficulty: "HARD", category: "Movies" },
  { text: "What was SRK's profession in Veer-Zaara?",
    options: ["Lawyer", "Army Officer", "Pilot", "Air Force officer"], correctIndex: 3,
    explanation: "He played Squadron Leader Veer Pratap Singh of the Indian Air Force.", difficulty: "MED", category: "Movies" },
  { text: "Which SRK movie featured the character \"Raj Mathur\"?",
    options: ["Rab Ne Bana Di Jodi", "Raju Ban Gaya Gentleman", "Mohabbatein", "Dilwale Dulhania Le Jayenge"], correctIndex: 1,
    explanation: "SRK plays Raj Mathur in 'Raju Ban Gaya Gentleman'.", difficulty: "HARD", category: "Movies" },
  { text: "Which SRK film was India's official Oscar entry?",
    options: ["Swades", "My Name Is Khan", "Paheli", "Chak De India"], correctIndex: 2,
    explanation: "'Paheli' (2005) was India's official entry for the Academy Awards.", difficulty: "HARD", category: "Awards" },
  { text: "Which SRK movie had the least opening among these?",
    options: ["Swades", "Ra.One", "Don 2", "Chennai Express"], correctIndex: 0,
    explanation: "'Swades' had a modest opening compared to the others.", difficulty: "HARD", category: "Movies" },
  { text: "In Chamatkar what was SRK's character name?",
    options: ["Sunil", "Sunder Srivastava", "Rahul Khanna", "Raj Aryan"], correctIndex: 1,
    explanation: "He played Sunder Srivastava in 'Chamatkar'.", difficulty: "HARD", category: "Movies" },
  { text: "What was SRK's first Filmfare Best Actor award-winning film?",
    options: ["Baazigar", "Darr", "Deewana", "Anjaam"], correctIndex: 0,
    explanation: "'Baazigar' (1993) earned him his first Filmfare Best Actor award.", difficulty: "MED", category: "Awards" },
  { text: "What was Kabir Khan's jersey number when he played for India in Chak De! India?",
    options: ["9", "10", "18", "16"], correctIndex: 0,
    explanation: "Kabir Khan wore jersey number 9 during his playing days for India.", difficulty: "HARD", category: "Movies" },
  { text: "Which was the first TV serial shot by Shah Rukh Khan?",
    options: ["Fauji", "Dil Dariya", "Circus", "Umeed"], correctIndex: 1,
    explanation: "'Dil Dariya' was shot first, though 'Fauji' aired earlier.", difficulty: "HARD", category: "Career" },
  { text: "Which SRK movie had no heroine opposite him?",
    options: ["Chak De India", "FAN", "Guddu", "Maya Memsaab"], correctIndex: 0,
    explanation: "'Chak De! India' had no romantic heroine opposite SRK.", difficulty: "MED", category: "Movies" },
  { text: "Which international film festival honoured Shah Rukh Khan with the Pardo alla Carriera (Career Leopard) in 2024?",
    options: ["Cannes Film Festival", "Berlin International Film Festival", "Locarno Film Festival", "Venice Film Festival"], correctIndex: 2,
    explanation: "The Locarno Film Festival honoured him with the Pardo alla Carriera in 2024.", difficulty: "HARD", category: "Awards" },
  { text: "How many honorary doctorates has Shah Rukh Khan received?",
    options: ["4", "6", "3", "5"], correctIndex: 3,
    explanation: "SRK has received 5 honorary doctorates.", difficulty: "HARD", category: "Awards" },
  { text: "Which SRK movie was produced under Dreamz Unlimited?",
    options: ["Main Hoon Na", "Om Shanti Om", "Swades", "Phir Bhi Dil Hai Hindustani"], correctIndex: 3,
    explanation: "'Phir Bhi Dil Hai Hindustani' (2000) was the first film under Dreamz Unlimited.", difficulty: "HARD", category: "Business" },
  { text: "FAN Feud Round! (Answers from the SRK Warriors global fan survey) Which SRK movie do fans consider most underrated?",
    options: ["FAN", "Swades", "Kabhi Haan Kabhi Naa", "Paheli"], correctIndex: 1,
    explanation: "Fan survey: 'Swades' was voted the most underrated.", difficulty: "EASY", category: "Fan Feud" },
  { text: "Which SRK movie makes fans cry the most?",
    options: ["My Name Is Khan", "Veer Zaara", "Swades", "Kal Ho Naa Ho"], correctIndex: 3,
    explanation: "Fan survey: 'Kal Ho Naa Ho' makes fans cry the most.", difficulty: "EASY", category: "Fan Feud" },
  { text: "Best SRK heroine?",
    options: ["Deepika Padukone", "Juhi Chawla", "Kajol", "Rani Mukerji"], correctIndex: 2,
    explanation: "Fan survey: Kajol voted the best SRK heroine.", difficulty: "EASY", category: "Fan Feud" },
  { text: "Best SRK friendship on screen?",
    options: ["Surinder & Bobby (Rab Ne Bana Di Jodi)", "Aman & Rohit (KHNH)", "SRK & Kajol (KKHH Friendship Phase)", "Kabir Khan & Team India (Chak De India)"], correctIndex: 2,
    explanation: "Fan survey: SRK & Kajol's KKHH friendship phase won.", difficulty: "EASY", category: "Fan Feud" },
  { text: "Most rewatchable SRK movie?",
    options: ["Kal Ho Naa Ho", "Om Shanti Om", "Chennai Express", "DDLJ"], correctIndex: 3,
    explanation: "Fan survey: 'DDLJ' is the most rewatchable.", difficulty: "EASY", category: "Fan Feud" },
  { text: "Best SRK movie climax?",
    options: ["Veer Zaara", "Jawan", "Chak De India", "Pathaan"], correctIndex: 0,
    explanation: "Fan survey: 'Veer Zaara' has the best climax.", difficulty: "EASY", category: "Fan Feud" },
  { text: "Most inspirational SRK character?",
    options: ["Kabir Khan", "Rizwan Khan", "Mohan Bhargav", "Surinder Sahni"], correctIndex: 2,
    explanation: "Fan survey: Mohan Bhargav voted most inspirational.", difficulty: "EASY", category: "Fan Feud" },
  { text: "Most romantic SRK character?",
    options: ["Rahul (KKHH)", "Veer Pratap Singh", "Raj Malhotra (DDLJ)", "Aman Mathur (KHNH)"], correctIndex: 1,
    explanation: "Fan survey: Veer Pratap Singh voted most romantic.", difficulty: "EASY", category: "Fan Feud" },
  { text: "Most stylish SRK look?",
    options: ["Don 1 & 2", "KING (2026 look)", "Pathaan", "Kabir Singh"], correctIndex: 0,
    explanation: "Fan survey: the Don 1 & 2 look voted most stylish.", difficulty: "EASY", category: "Fan Feud" },
  { text: "Which SRK movie deserved more appreciation?",
    options: ["FAN", "Raees", "Kabhi Haan Kabhi Naa", "Swades"], correctIndex: 3,
    explanation: "Fan survey: 'Swades' deserved more appreciation.", difficulty: "EASY", category: "Fan Feud" },
];
