import { PrismaClient, Difficulty } from "@prisma/client";
const prisma = new PrismaClient();

type Q = { text: string; options: string[]; correctIndex: number;
  explanation: string; difficulty: Difficulty; category: string };

const QUESTIONS: Q[] = [
  { text: "In which year did Shah Rukh Khan make his Bollywood film debut with 'Deewana'?",
    options: ["1990","1992","1994","1988"], correctIndex: 1,
    explanation: "'Deewana' released in 1992, marking SRK's Bollywood debut.",
    difficulty: "EASY", category: "Career" },
  { text: "Which two TV serials gave SRK his early fame before films?",
    options: ["Hum Log & Buniyaad","Fauji & Circus","Nukkad & Wagle","Byomkesh & Tehkikaat"], correctIndex: 1,
    explanation: "He starred in both 'Fauji' (1989) and 'Circus' (1989).",
    difficulty: "MED", category: "Career" },
  { text: "What is the name of the production company SRK co-founded in 2002?",
    options: ["Red Chillies Entertainment","Dharma Productions","Yash Raj Films","Excel Entertainment"],
    correctIndex: 0, explanation: "Red Chillies Entertainment was founded by SRK and Gauri Khan.",
    difficulty: "EASY", category: "Business" },
  { text: "In 'Dilwale Dulhania Le Jayenge' (1995), what is SRK's character's name?",
    options: ["Rahul","Raj","Aman","Veer"], correctIndex: 1,
    explanation: "He plays Raj Malhotra in DDLJ.", difficulty: "EASY", category: "Movies" },
  { text: "Which 2007 sports film featured SRK as a hockey coach?",
    options: ["Chak De! India","Goal","Patiala House","Jersey"], correctIndex: 0,
    explanation: "SRK played coach Kabir Khan in 'Chak De! India'.",
    difficulty: "EASY", category: "Movies" },
  { text: "What is the iconic pose Shah Rukh Khan is most famous for?",
    options: ["Folded arms","Outstretched arms","Hands on hips","Pointing finger"], correctIndex: 1,
    explanation: "His signature is the wide outstretched-arms pose.", difficulty: "EASY", category: "Iconic" },
  { text: "In 'My Name Is Khan' (2010), what condition does SRK's character have?",
    options: ["Autism","Asperger's syndrome","Dyslexia","Blindness"], correctIndex: 1,
    explanation: "Rizwan Khan has Asperger's syndrome.", difficulty: "MED", category: "Movies" },
  { text: "Which 2004 Yash Chopra film paired SRK with Rani Mukerji and Preity Zinta?",
    options: ["Veer-Zaara","Kabhi Alvida Naa Kehna","Mohabbatein","Chalte Chalte"], correctIndex: 0,
    explanation: "'Veer-Zaara' (2004) was directed by Yash Chopra.", difficulty: "MED", category: "Movies" },
  { text: "What is SRK's profession in 'Swades' (2004)?",
    options: ["Doctor","NASA scientist","Teacher","Banker"], correctIndex: 1,
    explanation: "Mohan Bhargava is a NASA scientist who returns to India.", difficulty: "MED", category: "Movies" },
  { text: "The song 'Chaiyya Chaiyya', shot atop a moving train, is from which film?",
    options: ["Dil Se","Asoka","Josh","Pardes"], correctIndex: 0,
    explanation: "'Chaiyya Chaiyya' is from 'Dil Se' (1998).", difficulty: "MED", category: "Music" },
  { text: "In 'Don' (2006), SRK remade a role originated by which actor?",
    options: ["Amitabh Bachchan","Rajesh Khanna","Dharmendra","Vinod Khanna"], correctIndex: 0,
    explanation: "Amitabh Bachchan played Don in the 1978 original.", difficulty: "MED", category: "Movies" },
  { text: "What is SRK's character name in 'Kabhi Khushi Kabhie Gham' (2001)?",
    options: ["Rahul Raichand","Rohan","Yashvardhan","Aman"], correctIndex: 0,
    explanation: "He plays Rahul Raichand, the adopted elder son.", difficulty: "EASY", category: "Movies" },
  { text: "In which year was SRK's sequel film 'Don 2' released?",
    options: ["2009","2011","2013","2008"], correctIndex: 1,
    explanation: "'Don 2' released in 2011.", difficulty: "MED", category: "Movies" },
  { text: "Who is SRK's leading co-star in 'Chennai Express' (2013)?",
    options: ["Deepika Padukone","Kajol","Anushka Sharma","Katrina Kaif"], correctIndex: 0,
    explanation: "Deepika Padukone starred as Meenamma.", difficulty: "EASY", category: "Movies" },
  { text: "Which IPL cricket team does SRK co-own?",
    options: ["Mumbai Indians","Kolkata Knight Riders","Chennai Super Kings","Delhi Capitals"], correctIndex: 1,
    explanation: "SRK co-owns Kolkata Knight Riders.", difficulty: "EASY", category: "Business" },
  { text: "On which date was Shah Rukh Khan born?",
    options: ["2 November 1965","1 January 1970","15 August 1962","5 May 1968"], correctIndex: 0,
    explanation: "He was born on 2 November 1965.", difficulty: "MED", category: "Personal" },
  { text: "In which city was Shah Rukh Khan born?",
    options: ["Mumbai","New Delhi","Lucknow","Hyderabad"], correctIndex: 1,
    explanation: "He was born in New Delhi.", difficulty: "MED", category: "Personal" },
  { text: "What is the name of SRK's Mumbai residence?",
    options: ["Jalsa","Mannat","Pratiksha","Antilia"], correctIndex: 1,
    explanation: "His bungalow is called 'Mannat'.", difficulty: "EASY", category: "Personal" },
  { text: "Which 2023 film marked SRK's comeback as an action spy thriller?",
    options: ["Pathaan","Jawan","Dunki","Tiger 3"], correctIndex: 0,
    explanation: "'Pathaan' (Jan 2023) was a blockbuster comeback.", difficulty: "EASY", category: "Movies" },
  { text: "Which 2023 Atlee-directed film featured SRK in a dual father-son role?",
    options: ["Jawan","Pathaan","Dunki","Raees"], correctIndex: 0,
    explanation: "'Jawan' (2023), directed by Atlee, featured SRK in dual roles.", difficulty: "MED", category: "Movies" },
  { text: "Which 2023 Rajkumar Hirani film starred SRK on an immigration theme?",
    options: ["Dunki","Jawan","Pathaan","Zero"], correctIndex: 0,
    explanation: "'Dunki' (Dec 2023) was directed by Rajkumar Hirani.", difficulty: "MED", category: "Movies" },
  { text: "In 'Zero' (2018), what is unique about SRK's character Bauua Singh?",
    options: ["He is blind","He is vertically challenged","He is mute","He is a twin"], correctIndex: 1,
    explanation: "Bauua Singh is a vertically challenged man.", difficulty: "MED", category: "Movies" },
  { text: "Which actress is SRK's most iconic recurring on-screen pairing?",
    options: ["Kajol","Rani Mukerji","Juhi Chawla","Madhuri Dixit"], correctIndex: 0,
    explanation: "Kajol is his most iconic recurring co-star.", difficulty: "EASY", category: "Movies" },
  { text: "Which honour did the French government award SRK in 2014?",
    options: ["Legion of Honour","Padma Shri","Croix de Guerre","Palme d'Or"], correctIndex: 0,
    explanation: "He received the Legion of Honour in 2014.", difficulty: "HARD", category: "Awards" },
  { text: "In 'Baazigar' (1993), SRK played which type of role, rare for a lead then?",
    options: ["A comedian","An anti-hero/villain","A police officer","A singer"], correctIndex: 1,
    explanation: "He played a negative anti-hero lead in 'Baazigar'.", difficulty: "MED", category: "Movies" },
  { text: "SRK played the title role in which 2002 Sanjay Leela Bhansali tragedy?",
    options: ["Devdas","Parineeta","Saawariya","Black"], correctIndex: 0,
    explanation: "He played the titular Devdas in the 2002 film.", difficulty: "EASY", category: "Movies" },
  { text: "How many Filmfare Best Actor awards has SRK won (record-tying)?",
    options: ["3","5","8","14"], correctIndex: 2,
    explanation: "He has won the Filmfare Best Actor award a record-tying 8 times.", difficulty: "HARD", category: "Awards" },
  { text: "What is the name of SRK's eldest son?",
    options: ["AbRam","Aryan","Ishaan","Arjun"], correctIndex: 1,
    explanation: "His eldest son is Aryan Khan.", difficulty: "EASY", category: "Personal" },
  { text: "What is the name of SRK's daughter?",
    options: ["Suhana","Sara","Nysa","Shanaya"], correctIndex: 0,
    explanation: "His daughter is Suhana Khan.", difficulty: "EASY", category: "Personal" },
  { text: "Which 2016 film had SRK playing both an obsessive fan and a superstar?",
    options: ["Fan","Raees","Dear Zindagi","Dilwale"], correctIndex: 0,
    explanation: "'Fan' (2016) featured SRK in dual roles as star Aryan and fan Gaurav.", difficulty: "MED", category: "Movies" },
  { text: "In 'Dear Zindagi' (2016), SRK plays a therapist opposite which lead actress?",
    options: ["Alia Bhatt","Deepika Padukone","Anushka Sharma","Kajol"], correctIndex: 0,
    explanation: "SRK plays therapist Jug; Alia Bhatt is the lead Kaira.", difficulty: "MED", category: "Movies" },
  { text: "Which of these brands has SRK NOT been a long-time ambassador for?",
    options: ["Pepsi","Hyundai","ICICI Bank","Tesla"], correctIndex: 3,
    explanation: "SRK has endorsed Pepsi, Hyundai and ICICI for years; never Tesla.", difficulty: "MED", category: "Business" },
  { text: "What nickname is SRK most popularly known by?",
    options: ["King Khan","The Boss","Thalaiva","Big B"], correctIndex: 0,
    explanation: "He is famously called 'King Khan' / 'Badshah of Bollywood'.", difficulty: "EASY", category: "Iconic" },
  { text: "What is SRK's character name in 'Kuch Kuch Hota Hai' (1998)?",
    options: ["Rahul","Raj","Aman","Sunil"], correctIndex: 0,
    explanation: "He plays Rahul Khanna in 'Kuch Kuch Hota Hai'.", difficulty: "EASY", category: "Movies" },
  { text: "The line 'Bade bade deshon mein aisi chhoti chhoti baatein' is from which film?",
    options: ["DDLJ","Kuch Kuch Hota Hai","Dil To Pagal Hai","Pardes"], correctIndex: 0,
    explanation: "It is an iconic line from DDLJ (1995).", difficulty: "MED", category: "Iconic" },
  { text: "Which actress made her Bollywood debut opposite SRK in 'Om Shanti Om' (2007)?",
    options: ["Deepika Padukone","Anushka Sharma","Katrina Kaif","Sonam Kapoor"], correctIndex: 0,
    explanation: "'Om Shanti Om' marked Deepika Padukone's debut.", difficulty: "MED", category: "Movies" },
  { text: "Which quiz show did SRK host in 2007, taking over from Amitabh Bachchan?",
    options: ["Kaun Banega Crorepati","Bigg Boss","Indian Idol","Dance India Dance"], correctIndex: 0,
    explanation: "SRK hosted the 3rd season of Kaun Banega Crorepati in 2007.", difficulty: "HARD", category: "TV" },
  { text: "What sport is central to the plot of 'Chak De! India'?",
    options: ["Cricket","Field Hockey","Football","Kabaddi"], correctIndex: 1,
    explanation: "It centres on the Indian women's field hockey team.", difficulty: "EASY", category: "Movies" },
  { text: "In 'Raees' (2017), what is the profession of SRK's character?",
    options: ["Bootlegger","Police officer","Politician","Doctor"], correctIndex: 0,
    explanation: "'Raees' features SRK as a bootlegger.", difficulty: "EASY", category: "Movies" },
  { text: "Which 1995 SRK film became the longest-running film in Indian cinema history?",
    options: ["DDLJ","Sholay","Mughal-e-Azam","Hum Aapke Hain Koun"], correctIndex: 0,
    explanation: "DDLJ has run continuously at Mumbai's Maratha Mandir for decades.", difficulty: "MED", category: "Iconic" },
];

async function main() {
  await prisma.question.deleteMany();
  await Promise.all(QUESTIONS.map((q, i) =>
    prisma.question.create({ data: { ...q, order: i } })));
  console.log(`Seeded ${QUESTIONS.length} questions`);
}
main().finally(() => prisma.$disconnect());
